---
- name: Prepare
  hosts: k8s
  tasks:
    - name: delete the kubeconfig if present
      file:
        path: '/tmp/molecule/kind/root/.kube/config'
        state: absent
      delegate_to: localhost

    - name: Fetch the kubeconfig
      fetch:
        dest: '/tmp/molecule/'
        src: /root/.kube/config

    - name: Wait for the Kubernetes API to become available
      uri:
        url: "https://localhost:8443/apis"
      register: result
      failed_when: false
    - debug: var=result

    - name: Wait for the Kubernetes API to become available
      uri:
        url: "https://localhost:8443/apis"
        status_code: 200
        validate_certs: no
      register: result
      until: (result.status|default(-1)) == 200
      retries: 60
      delay: 1

